'use strict';
const VERSION='css-ncii-complete-v11';
const CORE_CACHE=`${VERSION}-core`;
const CONTENT_CACHE=`${VERSION}-content`;
const CORE_ASSETS=[
  "./",
  "./index.html",
  "./css/style.css",
  "./js/data.js",
  "./js/app.js",
  "./manifest.webmanifest",
  "./assets/icons/icon-192.png",
  "./assets/icons/icon-512.png",
  "./assets/branding/softdev-logo.jpg"
];
const CONTENT_ASSETS=[
  "./assets/pages/m1-computer/page-01.jpg",
  "./assets/pages/m1-computer/page-02.jpg",
  "./assets/pages/m1-computer/page-03.jpg",
  "./assets/pages/m1-computer/page-04.jpg",
  "./assets/pages/m1-computer/page-05.jpg",
  "./assets/pages/m1-computer/page-06.jpg",
  "./assets/pages/m1-computer/page-07.jpg",
  "./assets/pages/m1-computer/page-08.jpg",
  "./assets/pages/m1-hardware/page-01.jpg",
  "./assets/pages/m1-hardware/page-02.jpg",
  "./assets/pages/m1-hardware/page-03.jpg",
  "./assets/pages/m1-hardware/page-04.jpg",
  "./assets/pages/m1-hardware/page-05.jpg",
  "./assets/pages/m1-hardware/page-06.jpg",
  "./assets/pages/m1-hardware/page-07.jpg",
  "./assets/pages/m1-hardware/page-08.jpg",
  "./assets/pages/m1-hardware/page-09.jpg",
  "./assets/pages/m1-hardware/page-10.jpg",
  "./assets/pages/m1-hardware/page-11.jpg",
  "./assets/pages/m1-hardware/page-12.jpg",
  "./assets/pages/m1-hardware/page-13.jpg",
  "./assets/pages/m1-hardware/page-14.jpg",
  "./assets/pages/m1-hardware/page-15.jpg",
  "./assets/pages/m1-hardware/page-16.jpg",
  "./assets/pages/m1-hardware/page-17.jpg",
  "./assets/pages/m1-hardware/page-18.jpg",
  "./assets/pages/m1-hardware/page-19.jpg",
  "./assets/pages/m1-hardware/page-20.jpg",
  "./assets/pages/m1-hardware/page-21.jpg",
  "./assets/pages/m1-hardware/page-22.jpg",
  "./assets/pages/m1-hardware/page-23.jpg",
  "./assets/pages/m1-hardware/page-24.jpg",
  "./assets/pages/m1-hardware/page-25.jpg",
  "./assets/pages/m1-hardware/page-26.jpg",
  "./assets/pages/m1-hardware/page-27.jpg",
  "./assets/pages/m1-hardware/page-28.jpg",
  "./assets/pages/m1-industry/page-01.jpg",
  "./assets/pages/m1-industry/page-02.jpg",
  "./assets/pages/m1-industry/page-03.jpg",
  "./assets/pages/m1-industry/page-04.jpg",
  "./assets/pages/m1-industry/page-05.jpg",
  "./assets/pages/m1-industry/page-06.jpg",
  "./assets/pages/m1-industry/page-07.jpg",
  "./assets/pages/m1-industry/page-08.jpg",
  "./assets/pages/m1-industry/page-09.jpg",
  "./assets/pages/m1-ohs/page-01.jpg",
  "./assets/pages/m1-ohs/page-02.jpg",
  "./assets/pages/m1-ohs/page-03.jpg",
  "./assets/pages/m1-ohs/page-04.jpg",
  "./assets/pages/m1-ohs/page-05.jpg",
  "./assets/pages/m1-ohs/page-06.jpg",
  "./assets/pages/m1-ohs/page-07.jpg",
  "./assets/pages/m1-ohs/page-08.jpg",
  "./assets/pages/m1-ohs/page-09.jpg",
  "./assets/pages/m1-ohs/page-10.jpg",
  "./assets/pages/m1-ohs/page-11.jpg",
  "./assets/pages/m1-ohs/page-12.jpg",
  "./assets/pages/m1-ohs/page-13.jpg",
  "./assets/pages/m1-quality/page-01.jpg",
  "./assets/pages/m1-quality/page-02.jpg",
  "./assets/pages/m1-quality/page-03.jpg",
  "./assets/pages/m1-quality/page-04.jpg",
  "./assets/pages/m1-quality/page-05.jpg",
  "./assets/pages/m1-quality/page-06.jpg",
  "./assets/pages/m1-tools/page-01.jpg",
  "./assets/pages/m1-tools/page-02.jpg",
  "./assets/pages/m1-tools/page-03.jpg",
  "./assets/pages/m1-tools/page-04.jpg",
  "./assets/pages/m1-tools/page-05.jpg",
  "./assets/pages/m1-tools/page-06.jpg",
  "./assets/pages/m1-tools/page-07.jpg",
  "./assets/pages/m1-tools/page-08.jpg",
  "./assets/pages/m2-assembly/page-01.jpg",
  "./assets/pages/m2-assembly/page-02.jpg",
  "./assets/pages/m2-assembly/page-03.jpg",
  "./assets/pages/m2-assembly/page-04.jpg",
  "./assets/pages/m2-assembly/page-05.jpg",
  "./assets/pages/m2-assembly/page-06.jpg",
  "./assets/pages/m2-bios/page-01.jpg",
  "./assets/pages/m2-bios/page-02.jpg",
  "./assets/pages/m2-bios/page-03.jpg",
  "./assets/pages/m2-bios/page-04.jpg",
  "./assets/pages/m2-bios/page-05.jpg",
  "./assets/pages/m2-bios/page-06.jpg",
  "./assets/pages/m2-bios/page-07.jpg",
  "./assets/pages/m2-bios/page-08.jpg",
  "./assets/pages/m2-bios/page-09.jpg",
  "./assets/pages/m2-bios/page-10.jpg",
  "./assets/pages/m2-bios/page-11.jpg",
  "./assets/pages/m2-disassembly/page-01.jpg",
  "./assets/pages/m2-disassembly/page-02.jpg",
  "./assets/pages/m2-disassembly/page-03.jpg",
  "./assets/pages/m2-disassembly/page-04.jpg",
  "./assets/pages/m2-disassembly/page-05.jpg",
  "./assets/pages/m2-disassembly/page-06.jpg",
  "./assets/pages/m2-drivers/page-01.jpg",
  "./assets/pages/m2-drivers/page-02.jpg",
  "./assets/pages/m2-drivers/page-03.jpg",
  "./assets/pages/m2-drivers/page-04.jpg",
  "./assets/pages/m2-drivers/page-05.jpg",
  "./assets/pages/m2-drivers/page-06.jpg",
  "./assets/pages/m2-drivers/page-07.jpg",
  "./assets/pages/m2-drivers/page-08.jpg",
  "./assets/pages/m2-io/page-01.jpg",
  "./assets/pages/m2-io/page-02.jpg",
  "./assets/pages/m2-io/page-03.jpg",
  "./assets/pages/m2-io/page-04.jpg",
  "./assets/pages/m2-io/page-05.jpg",
  "./assets/pages/m2-io/page-06.jpg",
  "./assets/pages/m2-io/page-07.jpg",
  "./assets/pages/m2-io/page-08.jpg",
  "./assets/pages/m2-io/page-09.jpg",
  "./assets/pages/m2-io/page-10.jpg",
  "./assets/pages/m2-os/page-01.jpg",
  "./assets/pages/m2-os/page-02.jpg",
  "./assets/pages/m2-os/page-03.jpg",
  "./assets/pages/m2-os/page-04.jpg",
  "./assets/pages/m2-os/page-05.jpg",
  "./assets/pages/m2-os/page-06.jpg",
  "./assets/pages/m2-os/page-07.jpg",
  "./assets/pages/m2-os/page-08.jpg",
  "./assets/pages/m2-software/page-01.jpg",
  "./assets/pages/m2-software/page-02.jpg",
  "./assets/pages/m2-software/page-03.jpg",
  "./assets/pages/m2-software/page-04.jpg",
  "./assets/pages/m2-software/page-05.jpg",
  "./assets/pages/m2-software/page-06.jpg",
  "./assets/pages/m2-software/page-07.jpg",
  "./assets/pages/m2-software/page-08.jpg",
  "./assets/pages/m2-software/page-09.jpg",
  "./assets/pages/m2-tests/page-01.jpg",
  "./assets/pages/m2-tests/page-02.jpg",
  "./assets/pages/m2-tests/page-03.jpg",
  "./assets/pages/m2-tests/page-04.jpg",
  "./assets/pages/m2-tests/page-05.jpg",
  "./assets/pages/m2-tests/page-06.jpg",
  "./assets/pages/m2-tests/page-07.jpg",
  "./assets/pages/m2-tests/page-08.jpg",
  "./assets/pages/m2-tests/page-09.jpg",
  "./assets/pages/m2-tests/page-10.jpg",
  "./assets/pages/m2-tests/page-11.jpg",
  "./assets/pages/m2-tests/page-12.jpg",
  "./assets/pages/m3-cables/page-01.jpg",
  "./assets/pages/m3-cables/page-02.jpg",
  "./assets/pages/m3-cables/page-03.jpg",
  "./assets/pages/m3-cables/page-04.jpg",
  "./assets/pages/m3-cables/page-05.jpg",
  "./assets/pages/m3-cables/page-06.jpg",
  "./assets/pages/m3-cables/page-07.jpg",
  "./assets/pages/m3-cables/page-08.jpg",
  "./assets/pages/m3-cables/page-09.jpg",
  "./assets/pages/m3-cables/page-10.jpg",
  "./assets/pages/m3-cables/page-11.jpg",
  "./assets/pages/m3-devices/page-01.jpg",
  "./assets/pages/m3-devices/page-02.jpg",
  "./assets/pages/m3-devices/page-03.jpg",
  "./assets/pages/m3-devices/page-04.jpg",
  "./assets/pages/m3-devices/page-05.jpg",
  "./assets/pages/m3-devices/page-06.jpg",
  "./assets/pages/m3-devices/page-07.jpg",
  "./assets/pages/m3-devices/page-08.jpg",
  "./assets/pages/m3-devices/page-09.jpg",
  "./assets/pages/m3-security/page-01.jpg",
  "./assets/pages/m3-security/page-02.jpg",
  "./assets/pages/m3-security/page-03.jpg",
  "./assets/pages/m3-security/page-04.jpg",
  "./assets/pages/m3-testing/page-01.jpg",
  "./assets/pages/m3-testing/page-02.jpg",
  "./assets/pages/m3-testing/page-03.jpg",
  "./assets/pages/m3-testing/page-04.jpg",
  "./assets/pages/m3-testing/page-05.jpg",
  "./assets/pages/m3-testing/page-06.jpg",
  "./assets/pages/m3-topology/page-01.jpg",
  "./assets/pages/m3-topology/page-02.jpg",
  "./assets/pages/m3-topology/page-03.jpg",
  "./assets/pages/m3-topology/page-04.jpg",
  "./assets/pages/m3-topology/page-05.jpg",
  "./assets/pages/m3-topology/page-06.jpg",
  "./assets/pages/m3-topology/page-07.jpg",
  "./assets/pages/m3-topology/page-08.jpg",
  "./assets/pages/m3-topology/page-09.jpg",
  "./assets/pages/m3-topology/page-10.jpg",
  "./assets/pages/m3-topology/page-11.jpg",
  "./assets/pages/m3-topology/page-12.jpg",
  "./assets/pages/m3-topology/page-13.jpg",
  "./assets/pages/m3-topology/page-14.jpg",
  "./assets/pages/m3-topology/page-15.jpg",
  "./assets/pages/m3-wireless/page-01.jpg",
  "./assets/pages/m3-wireless/page-02.jpg",
  "./assets/pages/m3-wireless/page-03.jpg",
  "./assets/pages/m3-wireless/page-04.jpg",
  "./assets/pages/m3-wireless/page-05.jpg",
  "./assets/pages/m3-wireless/page-06.jpg",
  "./assets/pages/m3-wireless/page-07.jpg",
  "./assets/pages/m3-wireless/page-08.jpg",
  "./assets/pages/m3-wireless/page-09.jpg",
  "./assets/pages/m3-wireless/page-10.jpg",
  "./assets/pages/m3-wireless/page-11.jpg",
  "./assets/pages/m3-wireless/page-12.jpg",
  "./assets/pages/m3-wireless/page-13.jpg",
  "./assets/pages/m3-wireless/page-14.jpg",
  "./assets/pages/m3-wireless/page-15.jpg",
  "./assets/pages/m3-wireless/page-16.jpg",
  "./assets/pages/m3-wireless/page-17.jpg",
  "./assets/pages/m3-wireless/page-18.jpg",
  "./assets/pages/m3-wireless/page-19.jpg",
  "./assets/pages/m4-boot/page-01.jpg",
  "./assets/pages/m4-boot/page-02.jpg",
  "./assets/pages/m4-boot/page-03.jpg",
  "./assets/pages/m4-boot/page-04.jpg",
  "./assets/pages/m4-boot/page-05.jpg",
  "./assets/pages/m4-boot/page-06.jpg",
  "./assets/pages/m4-client-server/page-01.jpg",
  "./assets/pages/m4-client-server/page-02.jpg",
  "./assets/pages/m4-client-server/page-03.jpg",
  "./assets/pages/m4-client-server/page-04.jpg",
  "./assets/pages/m4-client-server/page-05.jpg",
  "./assets/pages/m4-client-server/page-06.jpg",
  "./assets/pages/m4-modules/page-01.jpg",
  "./assets/pages/m4-modules/page-02.jpg",
  "./assets/pages/m4-modules/page-03.jpg",
  "./assets/pages/m4-modules/page-04.jpg",
  "./assets/pages/m4-modules/page-05.jpg",
  "./assets/pages/m4-services/page-01.jpg",
  "./assets/pages/m4-services/page-02.jpg",
  "./assets/pages/m4-services/page-03.jpg",
  "./assets/pages/m4-services/page-04.jpg",
  "./assets/pages/m4-services/page-05.jpg",
  "./assets/pages/m4-services/page-06.jpg",
  "./assets/pages/m4-services/page-07.jpg",
  "./assets/pages/m4-services/page-08.jpg",
  "./assets/pages/m4-services/page-09.jpg",
  "./assets/pages/m4-services/page-10.jpg",
  "./assets/pages/m4-services/page-11.jpg",
  "./assets/pages/m4-services/page-12.jpg",
  "./assets/pages/m4-services/page-13.jpg",
  "./assets/pages/m4-services/page-14.jpg",
  "./assets/pages/m4-services/page-15.jpg",
  "./assets/pages/m4-services/page-16.jpg",
  "./assets/pages/m4-services/page-17.jpg",
  "./assets/pages/m4-user-access/page-01.jpg",
  "./assets/pages/m4-user-access/page-02.jpg",
  "./assets/pages/m4-user-access/page-03.jpg",
  "./assets/pages/m4-user-access/page-04.jpg",
  "./assets/pages/m4-user-folder/page-01.jpg",
  "./assets/pages/m4-user-folder/page-02.jpg",
  "./assets/pages/m4-user-folder/page-03.jpg",
  "./assets/pages/m4-user-folder/page-04.jpg",
  "./assets/pages/m4-user-folder/page-05.jpg",
  "./assets/pages/m4-user-folder/page-06.jpg",
  "./assets/pages/m4-user-folder/page-07.jpg",
  "./assets/pages/m4-user-folder/page-08.jpg",
  "./assets/pages/m4-user-folder/page-09.jpg",
  "./assets/pages/m4-user-folder/page-10.jpg",
  "./assets/pages/m4-user-folder/page-11.jpg",
  "./assets/pages/m4-user-folder/page-12.jpg",
  "./assets/pages/m4-user-folder/page-13.jpg",
  "./assets/pages/m5-correcting/page-01.jpg",
  "./assets/pages/m5-correcting/page-02.jpg",
  "./assets/pages/m5-correcting/page-03.jpg",
  "./assets/pages/m5-correcting/page-04.jpg",
  "./assets/pages/m5-correcting/page-05.jpg",
  "./assets/pages/m5-correcting/page-06.jpg",
  "./assets/pages/m5-correcting/page-07.jpg",
  "./assets/pages/m5-diagnosing/page-01.jpg",
  "./assets/pages/m5-diagnosing/page-02.jpg",
  "./assets/pages/m5-diagnosing/page-03.jpg",
  "./assets/pages/m5-diagnosing/page-04.jpg",
  "./assets/pages/m5-diagnosing/page-05.jpg",
  "./assets/pages/m5-diagnosing/page-06.jpg",
  "./assets/pages/m5-diagnosing/page-07.jpg",
  "./assets/pages/m5-diagnosing/page-08.jpg",
  "./assets/pages/m5-diagnosing/page-09.jpg",
  "./assets/pages/m5-diagnosing/page-10.jpg",
  "./assets/pages/m5-inspecting/page-01.jpg",
  "./assets/pages/m5-inspecting/page-02.jpg",
  "./assets/pages/m5-inspecting/page-03.jpg",
  "./assets/pages/m5-inspecting/page-04.jpg",
  "./assets/pages/m5-inspecting/page-05.jpg",
  "./assets/pages/m5-inspecting/page-06.jpg",
  "./assets/pages/m5-inspecting/page-07.jpg",
  "./assets/pages/m5-inspecting/page-08.jpg",
  "./assets/pages/m5-inspecting/page-09.jpg",
  "./assets/pages/m5-inspecting/page-10.jpg",
  "./assets/pages/m5-maintaining/page-01.jpg",
  "./assets/pages/m5-maintaining/page-02.jpg",
  "./assets/pages/m5-maintaining/page-03.jpg",
  "./assets/pages/m5-maintaining/page-04.jpg",
  "./assets/pages/m5-maintaining/page-05.jpg",
  "./assets/pages/m5-maintaining/page-06.jpg",
  "./assets/pages/m5-maintaining/page-07.jpg",
  "./assets/pages/m5-maintaining/page-08.jpg",
  "./assets/pages/m5-maintaining/page-09.jpg",
  "./assets/pages/m5-planning/page-01.jpg",
  "./assets/pages/m5-planning/page-02.jpg",
  "./assets/pages/m5-planning/page-03.jpg",
  "./assets/pages/m5-planning/page-04.jpg",
  "./assets/pages/m5-planning/page-05.jpg",
  "./assets/pages/m5-planning/page-06.jpg",
  "./assets/pages/m5-planning/page-07.jpg",
  "./assets/pages/m5-planning/page-08.jpg",
  "./assets/pages/m5-planning/page-09.jpg",
  "./assets/pages/m5-planning/page-10.jpg",
  "./assets/source-pdfs/m1-computer.pdf",
  "./assets/source-pdfs/m1-hardware.pdf",
  "./assets/source-pdfs/m1-industry.pdf",
  "./assets/source-pdfs/m1-ohs.pdf",
  "./assets/source-pdfs/m1-quality.pdf",
  "./assets/source-pdfs/m1-tools.pdf",
  "./assets/source-pdfs/m2-assembly.pdf",
  "./assets/source-pdfs/m2-bios.pdf",
  "./assets/source-pdfs/m2-disassembly.pdf",
  "./assets/source-pdfs/m2-drivers.pdf",
  "./assets/source-pdfs/m2-io.pdf",
  "./assets/source-pdfs/m2-os.pdf",
  "./assets/source-pdfs/m2-software.pdf",
  "./assets/source-pdfs/m2-tests.pdf",
  "./assets/source-pdfs/m3-cables.pdf",
  "./assets/source-pdfs/m3-devices.pdf",
  "./assets/source-pdfs/m3-security.pdf",
  "./assets/source-pdfs/m3-testing.pdf",
  "./assets/source-pdfs/m3-topology.pdf",
  "./assets/source-pdfs/m3-wireless.pdf",
  "./assets/source-pdfs/m4-boot.pdf",
  "./assets/source-pdfs/m4-client-server.pdf",
  "./assets/source-pdfs/m4-modules.pdf",
  "./assets/source-pdfs/m4-services.pdf",
  "./assets/source-pdfs/m4-user-access.pdf",
  "./assets/source-pdfs/m4-user-folder.pdf",
  "./assets/source-pdfs/m5-correcting.pdf",
  "./assets/source-pdfs/m5-diagnosing.pdf",
  "./assets/source-pdfs/m5-inspecting.pdf",
  "./assets/source-pdfs/m5-maintaining.pdf",
  "./assets/source-pdfs/m5-planning.pdf"
];
const ALL_ASSETS=[...new Set([...CORE_ASSETS,...CONTENT_ASSETS])];
const absolute=url=>new URL(url,self.registration.scope).href;

async function cacheCore(){
  const cache=await caches.open(CORE_CACHE);
  await cache.addAll(CORE_ASSETS.map(absolute));
}
async function cacheOne(cache,url){
  const request=new Request(absolute(url),{cache:'reload',credentials:'same-origin'});
  const existing=await cache.match(request);
  if(existing)return true;
  const response=await fetch(request);
  if(!response.ok)throw new Error(`HTTP ${response.status} for ${url}`);
  await cache.put(request,response.clone());
  return true;
}
async function cacheStatus(){
  const core=await caches.open(CORE_CACHE),content=await caches.open(CONTENT_CACHE);
  let cached=0;
  for(const url of ALL_ASSETS){if(await core.match(absolute(url))||await content.match(absolute(url)))cached++;}
  return {cached,total:ALL_ASSETS.length,complete:cached===ALL_ASSETS.length,failed:0};
}
async function cacheAll(client){
  const cache=await caches.open(CONTENT_CACHE);
  let status=await cacheStatus();
  client?.postMessage({type:'OFFLINE_STATUS',...status});
  if(status.complete){client?.postMessage({type:'OFFLINE_COMPLETE',...status});return;}
  let cached=status.cached,failed=0;
  const pending=[];
  for(const url of ALL_ASSETS){
    const hit=await caches.match(absolute(url));
    if(!hit)pending.push(url);
  }
  for(let i=0;i<pending.length;i+=6){
    const batch=pending.slice(i,i+6);
    const results=await Promise.allSettled(batch.map(url=>cacheOne(cache,url)));
    results.forEach(result=>{if(result.status==='fulfilled')cached++;else failed++;});
    client?.postMessage({type:'OFFLINE_PROGRESS',cached,total:ALL_ASSETS.length,complete:false,failed});
  }
  status=await cacheStatus();status.failed=failed;
  client?.postMessage({type:'OFFLINE_COMPLETE',...status,complete:status.cached===status.total});
}

self.addEventListener('install',event=>{event.waitUntil(cacheCore().then(()=>self.skipWaiting()));});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('css-ncii-complete-')&&!key.startsWith(VERSION)).map(key=>caches.delete(key)))).then(()=>self.clients.claim()));});
self.addEventListener('message',event=>{
  const message=event.data||{};
  if(message.type==='CACHE_ALL')event.waitUntil(cacheAll(event.source));
  if(message.type==='GET_OFFLINE_STATUS')event.waitUntil(cacheStatus().then(status=>event.source?.postMessage({type:'OFFLINE_STATUS',...status})));
  if(message.type==='SKIP_WAITING')self.skipWaiting();
});
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET')return;
  const url=new URL(event.request.url);
  if(url.origin!==self.location.origin)return;
  if(event.request.mode==='navigate'){
    event.respondWith(fetch(event.request).then(response=>{const copy=response.clone();caches.open(CORE_CACHE).then(cache=>cache.put(absolute('./index.html'),copy));return response;}).catch(()=>caches.match(absolute('./index.html'))));
    return;
  }
  event.respondWith(caches.match(event.request).then(cached=>{
    if(cached)return cached;
    return fetch(event.request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CONTENT_CACHE).then(cache=>cache.put(event.request,copy));}return response;}).catch(()=>new Response('Offline content is unavailable.',{status:503,headers:{'Content-Type':'text/plain'}}));
  }));
});
